"""Add image_ref to Post and Comment

Revision ID: c042001b5118
Revises: 
Create Date: 2023-08-29 22:37:52.285029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c042001b5118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_ref', sa.String(length=100), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_ref', sa.String(length=100), nullable=True))
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('image_ref')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('image_ref')

    # ### end Alembic commands ###
